const ITEMS=[
{id:'A-01',name:'月面区画の権利証',cat:'RELIC',desc:'閉鎖された月面居住区の永久所有証書。',range:[280,620],value:540,quality:'良品',tell:'記録媒体の規格が第一次入植期と一致する。'},
{id:'A-02',name:'黒い培養鯉',cat:'BIO / ART',desc:'光をほとんど反射しない遺伝子改良種。',range:[180,560],value:310,quality:'並品',tell:'血統は本物だが、繁殖能力を失っている。'},
{id:'A-03',name:'第零区の物理鍵',cat:'RELIC',desc:'地図から削除された行政区の真鍮鍵。',range:[360,790],value:760,quality:'極上',tell:'複製痕がなく、区画封鎖以前の初期型。'},
{id:'A-04',name:'人工記憶「夏、1987」',cat:'DATA / ART',desc:'他人の夏を二時間だけ追体験できる。',range:[220,680],value:590,quality:'良品',tell:'編集版ではなく、失われた原記録に近い。'},
{id:'A-05',name:'未承認の義眼試作機',cat:'TECH',desc:'視界に三秒先の軌道を重ねるという。',range:[420,860],value:470,quality:'粗悪品',tell:'予測機能は停止。外装だけが試作機のもの。'},
{id:'A-06',name:'旧地下鉄の最終切符',cat:'RELIC',desc:'最終運行日の刻印が残る未使用券。',range:[140,430],value:390,quality:'良品',tell:'印刷番号が当日の記録と一致する。'},
{id:'A-07',name:'非合法人格バックアップ',cat:'DATA / ILLEGAL',desc:'所有者名を消された完全人格データ。',range:[390,900],value:820,quality:'極上',tell:'欠損率は0.8%。市場に出る水準ではない。'},
{id:'A-08',name:'放射線で変色する絵画',cat:'ART',desc:'展示環境に応じて色面が変化する。',range:[250,650],value:280,quality:'粗悪品',tell:'顔料は本物だが、支持体が交換されている。'},
{id:'A-09',name:'警察ドローンの中枢',cat:'TECH',desc:'廃棄機体から抜かれた判断モジュール。',range:[300,730],value:650,quality:'良品',tell:'事件記録が消去されずに残っている。'},
{id:'A-10',name:'雨の標本',cat:'RELIC',desc:'大気汚染以前の都市で採取された雨水。',range:[160,520],value:230,quality:'並品',tell:'年代は正しいが採取地点の証明が弱い。'}];
const QUESTS=[
{id:'relic',client:'市史蒐集院',title:'失われた街の証拠',text:'RELICを2点納品',need:2,reward:800,fail:100,match:i=>i.cat.includes('RELIC')},
{id:'quality',client:'無名の鑑定組合',title:'確かな品だけを',text:'良品または極上を2点納品',need:2,reward:700,fail:120,match:i=>['良品','極上'].includes(i.quality)},
{id:'high',client:'第七码頭の代理人',title:'一級資産の確保',text:'真価600 CR以上を2点納品',need:2,reward:950,fail:80,match:i=>i.value>=600}];
const PEOPLE=[{id:'reika',name:'鑑定士 レイカ',role:'材質・製法',face:'p0',trust:92},{id:'goro',name:'運び屋 ゴロウ',role:'出所・流通',face:'p1',trust:78},{id:'vera',name:'収集家 ヴェラ',role:'需要・希少性',face:'p2',trust:84},{id:'morgan',name:'仲介人 モーガン',role:'相場・競売',face:'p3',trust:86}];
const PLACES=[{id:'archive',name:'古書資料庫',role:'図録と記録を読む',pic:'l0',trust:90},{id:'market',name:'雨路地の露店',role:'同種品を探す',pic:'l1',trust:70},{id:'network',name:'公共ネット端末',role:'過去の取引を検索',pic:'l2',trust:82},{id:'warehouse',name:'第七码頭倉庫',role:'梱包と荷札を確認',pic:'l3',trust:88}];
const BIDDERS=[{name:'ヴェラ',face:'p2',factor:1.14},{name:'モーガン',face:'p3',factor:.82},{name:'匿名客09',face:'anon',factor:.96}];
const blank={screen:new URLSearchParams(location.search).has('new')?'name':'title',name:'',cash:1200,cycle:1,round:0,quest:null,lots:[],held:[],actions:4,clues:[],tab:'people',confidence:8,resolve:3,bid:60,leader:1,log:[],flash:'',won:null,paid:0,selected:[],delivery:null,prediction:null};
let state={...blank};if(document.location.pathname.includes('start-v12')||document.location.search.includes('new=1'))state.screen='name';const app=document.querySelector('#app'),SAVE='auction-file-save-v2',item=()=>state.lots[state.round],cr=n=>`${Math.max(0,Math.round(n)).toLocaleString()} CR`;
function persist(){try{localStorage.setItem(SAVE,JSON.stringify({...state,flash:''}))}catch{}}function hasSave(){try{return !!localStorage.getItem(SAVE)}catch{return false}}function clearSave(){try{localStorage.removeItem(SAVE)}catch{}}function load(){try{const saved=localStorage.getItem(SAVE);if(!saved)throw Error('no save');state={...blank,...JSON.parse(saved)};render()}catch{state={...blank};render()}}
function face(cls,s=''){return `<div class="face ${cls} ${s}"></div>`}function place(cls){return `<div class="place ${cls}"></div>`}
function shell(body){return `<main class="app screen-${state.screen}"><header class="bar"><button data-home>AUCTION FILE / 09</button><div>${state.name?`FILE ${state.name}　`:''}CASH <b>${cr(state.cash)}</b>　CYCLE ${state.cycle}</div></header>${body}${!['title','name'].includes(state.screen)?`<div class="sys"><button data-save>SAVE</button><button data-reset>RESET</button></div>`:''}${state.flash?`<div class="flash">${state.flash}</div>`:''}</main>`}
function title(){return shell(`<section class="title"><small>UNDERGROUND ESTATE AUCTION</small><h1>競売記録<br><span>AUCTION FILE</span></h1><p>依頼を受け、街を調べ、品物を仕入れ、納品する。</p><a class="solid" href="/start-v12.html">NEW FILE</a>${hasSave()?'<button class="line" data-continue>CONTINUE</button>':''}</section>`)}
function naming(){return shell(`<section class="naming"><small>PLAYER REGISTRATION</small><h1>主人公の名前</h1><p>競売記録に使用する名前を入力してください。</p><input id="player-name" maxlength="12" placeholder="NAME" autocomplete="off"><button class="solid" data-name>登録する</button><button class="line" data-home>戻る</button></section>`)}
function quest(){return shell(`<section class="quest"><header><small>CYCLE ${state.cycle} / CONTRACT</small><h1>依頼を選ぶ</h1><p>終了後、HOLDした品から納品物を指定する。</p></header><div>${QUESTS.map(q=>`<button data-quest="${q.id}"><small>${q.client}</small><h2>${q.title}</h2><p>${q.text}</p><dl><span>成功 ${cr(q.reward)}</span><span>失敗 ${cr(q.fail)}</span></dl></button>`).join('')}</div></section>`)}
function clueText(src,it){if(src==='reika'||src==='archive')return `「${it.tell}」`;if(src==='goro'||src==='warehouse')return it.value>=550?'厳重な梱包。扱いは一級品だった。':'一般貨物と同じ扱い。高級品には見えない。';if(src==='vera'||src==='market')return it.cat.includes('RELIC')||it.cat.includes('ART')?'同種を探す買い手が複数いる。':'買い手は限られる。熱くなる品ではない。';return `過去の取引記録：${Math.round(it.value*.76)}〜${Math.round(it.value*1.12)} CR`}
function explore(){const it=item(),sources=state.tab==='people'?PEOPLE:PLACES;return shell(`<section class="phase"><div><small>PHASE 1 / LOT ${state.round+1}</small><b>探索</b></div><div>行動 <strong>${state.actions}</strong> / 4</div></section><section class="explore"><article class="object"><small>${it.id} / ${it.cat}</small><h1>${it.name}</h1><p>${it.desc}</p><dl><div><dt>推定</dt><dd>${it.range[0]}—${it.range[1]} CR</dd></div><div><dt>自信</dt><dd>${state.confidence}%</dd></div></dl><aside><b>受注：${state.quest.title}</b><span>${state.quest.text}</span></aside></article><section class="search"><nav><button data-tab="people" class="${state.tab==='people'?'on':''}">人物</button><button data-tab="places" class="${state.tab==='places'?'on':''}">街・資料</button></nav><div>${sources.map(s=>`<button data-source="${s.id}" ${state.actions===0||state.clues.some(c=>c.id===s.id)?'disabled':''}>${s.face?face(s.face):place(s.pic)}<span><b>${s.name}</b><small>${s.role}</small></span></button>`).join('')}</div></section><aside class="notes"><h2>調査メモ</h2><div class="memo">${state.clues.length?state.clues.map(c=>`<p><b>${c.name}</b><span>${c.text}</span><i>確度 ${c.trust}%</i></p>`).join(''):'<em>まだ記録はない。</em>'}</div><div class="meter"><span>判断への自信</span><b>${state.confidence}%</b><i style="--v:${state.confidence}%"></i></div><button class="line" data-verify ${!state.clues.length||state.resolve===0?'disabled':''}>再確認 / 意志力 ${state.resolve}</button><button class="solid" data-auction ${state.actions>1?'disabled':''}>競売へ →</button></aside></section>`)}
function auction(){const it=item(),poor=state.cash<state.bid,leader=state.leader===3?'あなた':BIDDERS[state.leader].name;return shell(`<section class="phase"><div><small>PHASE 2 / LOT ${state.round+1}</small><b>競売</b></div><div>最高入札 <strong>${leader}</strong></div></section><section class="auction"><article><small>${it.id} / ${it.cat}</small><h1>${it.name}</h1><p>調査の自信 ${state.confidence}%</p><b>依頼対象かは納品時に判定</b></article><section class="price"><span>現在価格</span><strong>${cr(state.bid)}</strong><p>${leader} が値を上げた</p>${poor?predictionUI():`<div><button data-bid="10" ${state.bid+10>state.cash?'disabled':''}>+10</button><button data-bid="50" ${state.bid+50>state.cash?'disabled':''}>+50</button><button data-bid="100" ${state.bid+100>state.cash?'disabled':''}>+100</button><button data-pass>PASS</button></div>`}</section><aside><h2>参加者 / 入札履歴</h2>${BIDDERS.map((b,i)=>`<div class="bidder ${state.leader===i?'on':''}">${face(b.face,'small')}<b>${b.name}</b><i>${state.leader===i?'最高':'待機'}</i></div>`).join('')}<div class="history">${state.log.slice(-4).reverse().map(x=>`<p><b>${x.who}</b><span>${cr(x.amount)}</span></p>`).join('')}</div></aside></section>`)}
function predictionUI(){return `<div class="predict"><b>資金不足 / 市場予想で報酬を得る</b><p>落札者を予想してください。</p>${BIDDERS.map((x,i)=>`<button data-predict="${i}" class="${state.prediction===i?'on':''}">${x.name}</button>`).join('')}<button data-watch ${state.prediction===null?'disabled':''}>結果を見る</button></div>`}
function appraisal(){const it=state.won,profit=Math.round(it.value*.86)-state.paid;return shell(`<section class="appraisal"><small>APPRAISAL RESULT</small><h1>${it.name}</h1><div class="grade"><span>${it.quality}</span><b>${cr(it.value)}</b></div><p>${it.tell}</p><dl><div><dt>落札額</dt><dd>${cr(state.paid)}</dd></div><div><dt>即時売却額</dt><dd>${cr(Math.round(it.value*.86))}</dd></div><div><dt>売却損益</dt><dd>${profit>=0?'+':''}${cr(profit)}</dd></div></dl><footer><button class="line" data-hold>HOLD / 納品候補</button><button class="solid" data-sell>SELL / 換金</button></footer></section>`)}
function delivery(){return shell(`<section class="delivery"><header><small>CONTRACT DELIVERY</small><h1>納品物を指定</h1><p>${state.quest.client} / ${state.quest.text}</p></header><div class="inventory">${state.held.length?state.held.map((it,i)=>`<button data-select="${i}" class="${state.selected.includes(i)?'on':''}"><span>${it.cat}</span><b>${it.name}</b><small>${it.quality} / ${cr(it.value)}</small></button>`).join(''):'<p>HOLDした品物がありません。</p>'}</div><aside><b>選択 ${state.selected.length} 点</b><p>成功報酬 ${cr(state.quest.reward)}<br>失敗報酬 ${cr(state.quest.fail)}</p><button class="solid" data-deliver>納品する</button></aside></section>`)}
function report(){const d=state.delivery;return shell(`<section class="report"><small>CONTRACT REPORT</small><h1>${d.success?'依頼達成':'依頼未達'}</h1><p>${state.name}への支払報告</p><div><span>判定</span><b>${d.matches} / ${state.quest.need} 点</b><span>報酬</span><b>${cr(d.reward)}</b><span>次回持越金</span><b>${cr(state.cash)}</b></div><button class="solid" data-next-cycle>次の依頼を受ける</button><button class="line" data-save>SAVEして終了</button></section>`)}
function render(){const f={title,name:naming,quest,explore,auction,appraisal,delivery,report}[state.screen]||title;app.innerHTML=f()}
function newFile(){state={...blank,screen:'name'};render()}function startCycle(q){Object.assign(state,{screen:'explore',quest:q,round:0,lots:[...ITEMS].sort(()=>Math.random()-.5),actions:4,clues:[],confidence:8,resolve:3,bid:60,leader:1,log:[{who:BIDDERS[1].name,amount:60}],selected:[],delivery:null,prediction:null});persist();render()}
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-new]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();newFile()},true);
function prepNext(){state.round++;if(state.round>=10){state.screen='delivery'}else Object.assign(state,{screen:'explore',actions:4,clues:[],tab:'people',confidence:8,bid:60+state.round*10,leader:state.round%3,log:[{who:BIDDERS[state.round%3].name,amount:60+state.round*10}],prediction:null});persist();render()}
function endLot(won){if(won){state.cash-=state.bid;state.won=item();state.paid=state.bid;state.screen='appraisal';persist();render()}else prepNext()}
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.home!==undefined){state.screen='title';render();return}if(b.dataset.new!==undefined)return newFile();if(b.dataset.continue!==undefined)return load();if(b.dataset.name!==undefined){const n=document.querySelector('#player-name').value.trim();if(!n)return;state.name=n;state.screen='quest';persist();render();return}if(b.dataset.quest){startCycle(QUESTS.find(q=>q.id===b.dataset.quest));return}if(b.dataset.tab){state.tab=b.dataset.tab;render();return}if(b.dataset.source){const src=[...PEOPLE,...PLACES].find(x=>x.id===b.dataset.source);state.clues.push({id:src.id,name:src.name,text:clueText(src.id,item()),trust:src.trust});state.actions--;state.confidence=Math.min(96,state.confidence+Math.round(src.trust/5));render();return}if(b.dataset.verify!==undefined){state.resolve--;state.confidence=Math.min(99,state.confidence+15);render();return}if(b.dataset.auction!==undefined){state.screen='auction';persist();render();return}if(b.dataset.bid){const next=state.bid+Number(b.dataset.bid);if(next>state.cash)return;state.bid=next;state.leader=3;state.log.push({who:'あなた',amount:next});render();setTimeout(()=>{const i=(state.round+Number(b.dataset.bid))%3;if(state.bid+20<item().value*BIDDERS[i].factor){state.bid+=20;state.leader=i;state.log.push({who:BIDDERS[i].name,amount:state.bid})}render()},220);return}if(b.dataset.pass!==undefined){endLot(state.leader===3);return}if(b.dataset.predict){state.prediction=Number(b.dataset.predict);render();return}if(b.dataset.watch!==undefined){const winner=BIDDERS.map((x,i)=>({i,v:item().value*x.factor})).sort((a,z)=>z.v-a.v)[0].i,ok=winner===state.prediction,gain=ok?120:30;state.cash+=gain;state.flash=ok?`予想的中 +${gain} CR`:`参加報酬 +${gain} CR`;render();setTimeout(()=>{state.flash='';prepNext()},650);return}if(b.dataset.hold!==undefined){state.held.push(state.won);prepNext();return}if(b.dataset.sell!==undefined){state.cash+=Math.round(state.won.value*.86);prepNext();return}if(b.dataset.select){const i=Number(b.dataset.select),p=state.selected.indexOf(i);p<0?state.selected.push(i):state.selected.splice(p,1);render();return}if(b.dataset.deliver!==undefined){const chosen=state.selected.map(i=>state.held[i]),matches=chosen.filter(state.quest.match).length,success=matches>=state.quest.need,reward=success?state.quest.reward:state.quest.fail;state.cash+=reward;state.held=state.held.filter((_,i)=>!state.selected.includes(i));state.delivery={success,matches,reward};state.screen='report';persist();render();return}if(b.dataset.nextCycle!==undefined){state.cycle++;state.screen='quest';state.quest=null;state.selected=[];persist();render();return}if(b.dataset.save!==undefined){persist();state.flash='SAVED';render();setTimeout(()=>{state.flash='';render()},450);return}if(b.dataset.reset!==undefined){localStorage.removeItem(SAVE);state={...blank};render()}});render();
